// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrFtdnOJVgjJ78NEvgMMR-OZ1fro3ub9E',
    appId: '1:139898466496:web:7af0427c9eb5464218bd25',
    messagingSenderId: '139898466496',
    projectId: 'task-management-625e9',
    authDomain: 'task-management-625e9.firebaseapp.com',
    storageBucket: 'task-management-625e9.appspot.com',
    measurementId: 'G-1ZKWWMHFHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTC23jjXi6kHiqf_ueuUvML0a5JzHb8B8',
    appId: '1:139898466496:android:efb14fa5cc7b937618bd25',
    messagingSenderId: '139898466496',
    projectId: 'task-management-625e9',
    storageBucket: 'task-management-625e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxMZUQsPPxfoU87ZrS5zhxWpG4ThTfnmQ',
    appId: '1:139898466496:ios:9f844cb580676f6b18bd25',
    messagingSenderId: '139898466496',
    projectId: 'task-management-625e9',
    storageBucket: 'task-management-625e9.appspot.com',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrFtdnOJVgjJ78NEvgMMR-OZ1fro3ub9E',
    appId: '1:139898466496:web:190f0a55b614dc5d18bd25',
    messagingSenderId: '139898466496',
    projectId: 'task-management-625e9',
    authDomain: 'task-management-625e9.firebaseapp.com',
    storageBucket: 'task-management-625e9.appspot.com',
    measurementId: 'G-65XDQY18B1',
  );

}